// Source code is decompiled from a .class file using FernFlower decompiler (from Intellij IDEA).
package superscary.hotswap;

import java.util.stream.Collectors;
import net.minecraft.block.Block;
import net.minecraft.block.Blocks;
import net.minecraft.client.Minecraft;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegistryEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber;
import net.minecraftforge.fml.common.Mod.EventBusSubscriber.Bus;
import net.minecraftforge.fml.event.lifecycle.FMLClientSetupEvent;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.event.lifecycle.InterModEnqueueEvent;
import net.minecraftforge.fml.event.lifecycle.InterModProcessEvent;
import net.minecraftforge.fml.event.server.FMLServerStartingEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * So I definitely did not clean up the code generated by the mod template, and I also did not remove the comments generated by the mod template, so here we are.
 * Most of this stuff is essentially useless, since the only stuff that matters is in the constructor and RegistryEvents. I honestly have no idea why I left it like this.
 * 
 * Luckily, this was made before "vibe coding" was a thing, so I can basically say I either forgot to remove the template code, or I just left it in for fun. Either way, it is what it is.
 */
@Mod("hotswap")
public class HotSwap {
   private static final Logger LOGGER = LogManager.getLogger();

   public HotSwap() {
      FMLJavaModLoadingContext.get().getModEventBus().addListener(this::setup);
      FMLJavaModLoadingContext.get().getModEventBus().addListener(this::enqueueIMC);
      FMLJavaModLoadingContext.get().getModEventBus().addListener(this::processIMC);
      FMLJavaModLoadingContext.get().getModEventBus().addListener(this::doClientStuff);
      MinecraftForge.EVENT_BUS.register(this);
   }

   private void setup(FMLCommonSetupEvent event) {
      LOGGER.info("HELLO FROM PREINIT");
      LOGGER.info("DIRT BLOCK >> {}", Blocks.field_150346_d.getRegistryName());
   }

   private void doClientStuff(FMLClientSetupEvent event) {
      LOGGER.info("Got game settings {}", ((Minecraft)event.getMinecraftSupplier().get()).field_71474_y);
   }

   private void enqueueIMC(InterModEnqueueEvent event) {
   }

   private void processIMC(InterModProcessEvent event) {
      LOGGER.info("Got IMC {}", event.getIMCStream().map((m) -> m.getMessageSupplier().get()).collect(Collectors.toList()));
   }

   @SubscribeEvent
   public void onServerStarting(FMLServerStartingEvent event) {
      LOGGER.info("HELLO from server starting");
   }

   @EventBusSubscriber(
      bus = Bus.MOD
   )
   public static class RegistryEvents {
      public RegistryEvents() {
      }

      @SubscribeEvent
      public static void onBlocksRegistry(RegistryEvent.Register<Block> blockRegistryEvent) {
         HotSwap.LOGGER.info("HELLO from Register Block");
      }
   }
}
